version: "3"

services:
  server:
    image: ghcr.io/oxcom/amnezia-wg:${IMAGE_TAG}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      WG_IFACE: ${WG_IFACE}
      WG_PORT: ${WG_PORT}
      WG_ADDRESS: ${WG_ADDRESS}
      WG_SUBNET: ${WG_SUBNET}
      WG_ENDPOINT: ${WG_ENDPOINT}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    ports:
      - "${WG_PORT}:51820/udp"
    volumes:
      - ./data/server:/data
    restart: unless-stopped

  ui:
    image: ghcr.io/oxcom/amnezia-wg-ui:${IMAGE_TAG}
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/www:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt
    restart: unless-stopped


  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt
    # контейнер "по требованию": запускать командой docker compose run --rm certbot ...
    entrypoint: ["certbot"]
